In [31]:
import os
import numpy as np
import pandas as pd
import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn import tree, metrics
data =pd.read_csv('car.data',names=['buying','maint','doors','persons','lug_boot','safety','class'])
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [28]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
class       1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
data['class'],class_names = pd.factorize(data['class'])


In [6]:
print(class_names)
print(data['class'].unique())

Index(['unacc', 'acc', 'vgood', 'good'], dtype='object')
[0 1 2 3]


In [7]:
data['buying'],_ = pd.factorize(data['buying'])
data['maint'],_ = pd.factorize(data['maint'])
data['doors'],_ = pd.factorize(data['doors'])
data['persons'],_ = pd.factorize(data['persons'])
data['lug_boot'],_ = pd.factorize(data['lug_boot'])
data['safety'],_ = pd.factorize(data['safety'])
data.head()

buying  maint  doors  persons  lug_boot  safety  class
0       0      0      0        0         0       0      0
1       0      0      0        0         0       1      0
2       0      0      0        0         0       2      0
3       0      0      0        0         1       0      0
4       0      0      0        0         1       1      0

In [17]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
class       1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB


In [9]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [18]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state=23)


In [22]:
clf_entropy = DecisionTreeClassifier( criterion = "entropy", random_state = 100,  max_depth = 6, min_samples_leaf = 6)     
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=6, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [32]:
y_pred = clf_entropy.predict(X_test) 
print("Predicted values:") 
print(y_pred) 
    
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred)) 
        
      
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100) 
    
      
print("Report : ", classification_report(y_test, y_pred))

Predicted values:
[0 0 2 1 0 2 3 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1
 3 0 0 0 0 1 1 1 0 0 1 0 0 0 2 3 0 0 0 2 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1
 0 1 0 0 0 0 1 0 3 0 0 0 0 0 0 0 0 1 1 3 0 0 1 0 0 3 0 0 0 1 1 0 0 1 1 0 0
 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 3 0 2 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 2 0
 0 0 0 3 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0
 0 0 1 0 3 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 2 1 0 1 0 0 0 0 0 0 0 1 1 0
 0 1 0 1 0 0 3 3 1 0 0 1 0 0 0 0 0 1 0 1 2 3 1 0 1 0 0 1 1 0 0 1 0 3 0 0 0
 0]
Confusion Matrix:  [[176  14   0   1]
 [  1  45   2   3]
 [  0   2   7   0]
 [  0   0   0   9]]
Accuracy :  91.15384615384615
Report :               precision    recall  f1-score   support

          0       0.99      0.92      0.96       191
          1       0.74      0.88      0.80        51
          2       0.78      0.78      0.78         9
          3       0.69      1.00      0.82         9

avg / total       0.93      0.91      0.92       2